setwd("~/Documents/Online Classes/Coursera/Exploratory Data Analysis/")
lines = grep("^[1|2]/2/2007", readLines("./household_power_consumption.txt"))
df = read.table("./household_power_consumption.txt",sep=";",skip=(lines[1]-1),nrow=length(lines))
colnames(df) = c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
df$Date = as.character.Date(df$Date)
df$Date = as.Date(df$Date, format="%d/%m/%Y")
hist(df$Global_active_power,col="red",main="Global Active Power", ylab = "Frequency", xlab = "Global Active Power (kilowatts)")
dev.copy(png, file="plot1.png", height=480, width=480, units="px")
dev.off()
